### ISSUE TITLE
Gem version and library version are different

### ISSUE THREAD

**Issue by stomar** [ruby/csv#10]
Gem version as currently defined in the gemspec is 1.0.0.

But:

``` sh
$ ruby -r csv -e "p CSV::VERSION"
"2.4.8"
```

**Comment by hsbt** [comment]
@stomar Good catch... I missed it version before Ruby 2.5.0-rc1. I'm going to bump it version to 2.5.0 for final release.

**Comment by stevendaniels** [comment]
@hsbt, @stomar - Based on the [feature issue on ruby-lang](https://bugs.ruby-lang.org/issues/5481) I assumed that the CSV gem version would be independent of the Ruby version. Since the development of the two are independent, does it make sense to keep them the same?

[This note](https://bugs.ruby-lang.org/issues/5481#note-49) in particular led me to believe that CSV/Ruby versioning would be separate:
> BTW there should be process in place which ensures, that the libraries are properly versioned, i.e. if something is changed, it cannot have the same version as already released library (see #7761 and #7762).

Thoughts?

**Comment by kou** [comment]
Yes. You're right.

**Comment by stomar** [comment]
@stevendaniels I don't think the gem and Ruby versions should or can be kept the same. I only wanted to point out that CSV::VERSION and gemspec version did not match, which IMO they should. I have no idea what the "correct" version of CSV should be.

**Comment by aprescott** [comment]
I came into this issue as part of diagnosing a change to `CSV.generate`, described at https://bugs.ruby-lang.org/issues/9988.

In short it looks like `CSV.generate` changed functionality between Ruby 2.4.4 and 2.5.0, even though `CSV::VERSION` remains 2.4.8 between the two versions. I encountered this during a Ruby upgrade which broke some tests.

Before:

```ruby
RUBY_VERSION
# => "2.4.4"
require "csv"
# => true
CSV::VERSION
# => "2.4.8"
::CSV.generate(headers: ["Foo"], write_headers: true) { |csv| }
# => ""
```

After:

```ruby
RUBY_VERSION
# => "2.5.0"
require "csv"
# => true
CSV::VERSION
# => "2.4.8"
::CSV.generate(headers: ["Foo"], write_headers: true) { |csv| }
# => "Foo\n"
```

I'm trying to understand how this repo is used by Ruby as a gem versus [Ruby's own `csv.rb`](https://github.com/ruby/ruby/blob/v2_5_0/lib/csv.rb). Maybe someone could help me understand what's going on here?

* The [Ruby 2.5.0 release notes](https://www.ruby-lang.org/en/news/2017/12/25/ruby-2-5-0-released/) describe csv being promoted to a default gem.
* Ruby 2.5.0 has its own `lib/csv.rb`: https://github.com/ruby/ruby/blob/v2_5_0/lib/csv.rb.
* 2.5.0 also has `csv.gemspec`: https://github.com/ruby/ruby/blob/v2_5_0/lib/csv.gemspec.
* Ruby's own 2.5.0 sets `CSV::VERSION` as 2.4.8: https://github.com/ruby/ruby/blob/v2_5_0/lib/csv.rb#L211.

(The above seem true for 2.5.1, as well.)

If Ruby has `csv.gemspec` to pull in csv as a default gem, is a separately installed gem ever used instead of Ruby's own `lib/csv.rb`? (That may be a stupid question — I don't know how Ruby's default gems work!) As recently as https://github.com/ruby/ruby/commit/5c1941a9be56a979c27d740370b781882d344f79 it looks like the csv gem is being vendored.

**Comment by kou** [comment]
> is a separately installed gem ever used instead of Ruby's own `lib/csv.rb`?

Yes.

NOTE: You should not reuse a closed issue. You should open a new issue with a link to a closed issue.

**Comment by aprescott** [comment]
@kou I originally wrote my comment as a new issue, for that exact reason, but felt it potentially overlapped so much with this that a comment here was more appropriate, where the context lives. Would you prefer I move my question into a new issue? I have a further question about what "yes" means, since I wasn't clear in my original.

**Comment by kou** [comment]
Yes please.
