### ISSUE TITLE
2.5.0 / no docs?

### ISSUE THREAD

**Issue by jm3** [ruby/csv#9]
Is this Ruby's official CSV library now? I tried using FasterCSV with ruby 2.4.0, but it bails with an error requiring I use "ruby 1.9 csv" instead. Since this vode is available as the official `ruby/csv` namespace on Github, I assume that this is that gem, but there's no documentation, and the gemspec says that 2.5.0 is the minimum required ruby version? Should I be looking at the FasterCSV docs, is this just that, directly moved over?

If I'm in the wrong place, please point me to the docs for whatever CSV gem that works with 2.4.0.

**Comment by stomar** [comment]
FasterCSV replaced Ruby‘s previous CSV library a considerable time ago (maybe since 1.9, I didn‘t check) and has been shipped with all Ruby releases since then, as CSV library. So, requiring “csv“ is enough. You find the docs with all the other documentation for Ruby’s stdlib classes.

This gem exists because with 2.5 the stdlib gets „gemified“. CSV will continue to get shipped with Ruby releases (afaik; occasionally libraries get removed), but it will be possible to update the library independently of Ruby by installing a newer gem version, e.g. in case of security fixes.

**Comment by stevendaniels** [comment]
@hsbt  - @stomar's answer clears up this issue. It can be closed.
